apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  clusterIP: None
  selector:
    app: nginx
  ports:
  - port: 80        # must be an integer, not "80"
    targetPort: 80  # optional but good practice
