apiVersion: apps/v1
kind: StatefulSet
metadata:                   ##ekhane alada kore pod name deya hoyna like deployment,,ekhane metadata.name=web means replica 3 te means pod name hobe web-0,web-1,web-2.
  name: web
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: "nginx"
  replicas: 3
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html   ### then sei persistent vol ta container ar vetor ay path a mount kora hoy
  volumeClaimTemplates:               ### persistentvol banano hoy for pods...means under spec for pods.
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ebs
      resources:
        requests:
          storage: 1Gi
